/**
 * Pure aggregation helpers for the two Sciverse workflow tools
 * (`sciverse_trend_scan`, `sciverse_evidence_pack`). Kept free of I/O so the
 * pipeline logic is unit-testable without the SDK or network.
 * @module dsh-scholar-find/sciverse/aggregate
 */

/** Compact paper view used by the trend scanner (fields already projected). */
export interface TrendPaper {
  unique_id?: string
  title?: string
  citation_count?: number
  venue?: string
  year?: number
  doi?: string
}

/** A top-venue bucket: normalized venue name + paper count in the sampled pool. */
export interface TrendVenue {
  venue: string
  count: number
}

/** One processed claim for sciverse_evidence_pack. */
export interface EvidenceItem {
  claim: string
  /** Verbatim source passage (truncated). Never generated by the model. */
  quote: string
  chunk_id?: string
  doc_id?: string
  offset?: number
  page_no?: number
  title?: string
  /** Raw semantic score of the best hit. */
  score?: number
  /** Round(score, 2) — matches the cookiebook's confidence convention. */
  confidence?: number
  /** True when the slice read at doc_id+offset contains the quote. */
  verified: boolean
  /** True when a hit was found and its score met minScore. */
  matched: boolean
  source_type?: string
}

const YEAR_MIN = 1800
const YEAR_MAX = 2100

/**
 * Resolve a requested year span with defaults (last 5 years) and a hard cap.
 * Returns the validated range or a validation error message.
 */
export function resolveYearRange(
  yearFrom?: number,
  yearTo?: number,
  maxSpan = 10,
): { ok: true; yearFrom: number; yearTo: number; years: number[] } | { ok: false; error: string } {
  const to = typeof yearTo === 'number' && Number.isFinite(yearTo) ? Math.trunc(yearTo) : new Date().getFullYear()
  const from = typeof yearFrom === 'number' && Number.isFinite(yearFrom) ? Math.trunc(yearFrom) : to - 4
  if (from < YEAR_MIN || to > YEAR_MAX) return { ok: false, error: `years must be within ${YEAR_MIN}..${YEAR_MAX}.` }
  if (from > to) return { ok: false, error: `year_from (${from}) must be <= year_to (${to}).` }
  const span = to - from + 1
  if (span > maxSpan) return { ok: false, error: `span of ${span} years exceeds the ${maxSpan}-year cap; narrow the range.` }
  const years: number[] = []
  for (let y = from; y <= to; y++) years.push(y)
  return { ok: true, yearFrom: from, yearTo: to, years }
}

/** Sort by citation_count desc (missing = 0) and keep the top n. */
export function topByCitation(papers: readonly Record<string, unknown>[], n: number): TrendPaper[] {
  return [...papers]
    .sort((a, b) => Number(b.citation_count ?? 0) - Number(a.citation_count ?? 0))
    .slice(0, Math.max(0, n))
    .map((p) => ({
      unique_id: typeof p.unique_id === 'string' ? p.unique_id : undefined,
      title: typeof p.title === 'string' ? p.title : undefined,
      citation_count: typeof p.citation_count === 'number' ? p.citation_count : undefined,
      venue: typeof p.publication_venue_name_unified === 'string' ? p.publication_venue_name_unified : undefined,
      year: typeof p.publication_published_year === 'number' ? p.publication_published_year : undefined,
      doi: typeof p.doi === 'string' ? p.doi : undefined,
    }))
}

/** Count normalized venue names in a paper pool and keep the top n (most frequent). */
export function topVenues(papers: readonly Record<string, unknown>[], n: number): TrendVenue[] {
  const counts = new Map<string, number>()
  for (const p of papers) {
    const v = p.publication_venue_name_unified
    if (typeof v !== 'string' || !v) continue
    counts.set(v, (counts.get(v) ?? 0) + 1)
  }
  return [...counts.entries()]
    .sort((a, b) => b[1] - a[1] || a[0].localeCompare(b[0]))
    .slice(0, Math.max(0, n))
    .map(([venue, count]) => ({ venue, count }))
}

/**
 * Pick the best semantic hit for a claim: the highest-score hit overall, and
 * whether it clears the caller's score threshold. A hit exists but scores below
 * the threshold -> matched=false, so the caller can report "weak evidence".
 */
export function pickEvidenceHit(
  hits: readonly Record<string, unknown>[],
  minScore: number,
): { hit: Record<string, unknown> | undefined; matched: boolean } {
  if (!hits.length) return { hit: undefined, matched: false }
  const best = [...hits].sort((a, b) => Number(b.score ?? 0) - Number(a.score ?? 0))[0]!
  return { hit: best, matched: Number(best.score ?? 0) >= minScore }
}

/** Normalize text for quote verification: collapse whitespace, lower case. */
export function normalizeText(s: string): string {
  return s.replace(/\s+/g, ' ').trim().toLowerCase()
}

/**
 * Verify a quote against a full-text slice: the slice read at doc_id+offset
 * must contain the (normalized) quote text. Handles the common case where the
 * slice starts mid-sentence but still contains the quoted passage verbatim.
 * An empty slice is never a verification (no bytes == no evidence).
 */
export function verifyQuoteInSlice(slice: string, quote: string): boolean {
  const s = normalizeText(slice)
  const q = normalizeText(quote)
  if (!s || !q) return false
  return s.includes(q) || q.includes(s)
}

/** Build a lossless-safe evidence item from a hit plus its verification verdict. */
export function buildEvidenceItem(claim: string, hit: Record<string, unknown> | undefined, opts: { matched: boolean; verified: boolean; quoteMax?: number }): EvidenceItem {
  const quoteMax = opts.quoteMax ?? 600
  const quote = typeof hit?.chunk === 'string' ? hit.chunk : typeof hit?.abstract === 'string' ? hit.abstract : ''
  const score = typeof hit?.score === 'number' ? hit.score : undefined
  return {
    claim,
    quote: quote.slice(0, quoteMax),
    chunk_id: typeof hit?.chunk_id === 'string' ? hit.chunk_id : undefined,
    doc_id: typeof hit?.doc_id === 'string' ? hit.doc_id : undefined,
    offset: typeof hit?.offset === 'number' ? hit.offset : undefined,
    page_no: typeof hit?.page_no === 'number' ? hit.page_no : undefined,
    title: typeof hit?.title === 'string' ? hit.title : undefined,
    score,
    confidence: score !== undefined ? Math.round(score * 100) / 100 : undefined,
    verified: opts.verified,
    matched: opts.matched,
    source_type: typeof hit?.source_type === 'string' ? hit.source_type : undefined,
  }
}
